# Generated by Django 5.2.2 on 2025-07-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
