# Generated by Django 5.2.2 on 2025-07-07 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_salon_service_salon_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon_service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.salon_service_category'),
        ),
    ]
