# Generated by Django 5.2.2 on 2025-06-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branches',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='App1.salonbranch'),
        ),
    ]
