# Generated by Django 5.2.2 on 2025-07-11 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_admin_user_roles_delete_superadmin_admin_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_v', models.BooleanField(default=False)),
                ('roles_v', models.BooleanField(default=False)),
                ('roles_a', models.BooleanField(default=False)),
                ('roles_e', models.BooleanField(default=False)),
                ('roles_d', models.BooleanField(default=False)),
                ('users_v', models.BooleanField(default=False)),
                ('users_a', models.BooleanField(default=False)),
                ('users_e', models.BooleanField(default=False)),
                ('users_d', models.BooleanField(default=False)),
                ('vendors_v', models.BooleanField(default=False)),
                ('vendors_a', models.BooleanField(default=False)),
                ('vendors_e', models.BooleanField(default=False)),
                ('vendors_d', models.BooleanField(default=False)),
                ('clients_v', models.BooleanField(default=False)),
                ('clients_a', models.BooleanField(default=False)),
                ('clients_e', models.BooleanField(default=False)),
                ('clients_d', models.BooleanField(default=False)),
                ('category_v', models.BooleanField(default=False)),
                ('category_a', models.BooleanField(default=False)),
                ('category_e', models.BooleanField(default=False)),
                ('category_d', models.BooleanField(default=False)),
                ('services_v', models.BooleanField(default=False)),
                ('services_a', models.BooleanField(default=False)),
                ('services_e', models.BooleanField(default=False)),
                ('services_d', models.BooleanField(default=False)),
                ('schedule_v', models.BooleanField(default=False)),
                ('schedule_a', models.BooleanField(default=False)),
                ('schedule_e', models.BooleanField(default=False)),
                ('schedule_d', models.BooleanField(default=False)),
                ('booking_v', models.BooleanField(default=False)),
                ('booking_a', models.BooleanField(default=False)),
                ('booking_e', models.BooleanField(default=False)),
                ('booking_d', models.BooleanField(default=False)),
                ('payment_v', models.BooleanField(default=False)),
                ('payment_a', models.BooleanField(default=False)),
                ('payment_e', models.BooleanField(default=False)),
                ('payment_d', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='App1.roles')),
            ],
        ),
    ]
