# Generated by Django 5.2.2 on 2025-07-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_rolepermissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolepermissions',
            old_name='booking_a',
            new_name='bookings_a',
        ),
        migrations.RenameField(
            model_name='rolepermissions',
            old_name='booking_d',
            new_name='bookings_d',
        ),
        migrations.RenameField(
            model_name='rolepermissions',
            old_name='booking_e',
            new_name='bookings_e',
        ),
        migrations.RenameField(
            model_name='rolepermissions',
            old_name='booking_v',
            new_name='bookings_v',
        ),
    ]
