# Generated by Django 5.2.2 on 2025-07-02 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_superadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('service_category_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='service',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='service',
            name='estimated_time_min',
        ),
        migrations.RemoveField(
            model_name='service',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='salon',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.service_category'),
        ),
    ]
