# Generated by Django 5.2.2 on 2025-07-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_rename_booking_a_rolepermissions_bookings_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermissions',
            name='branches_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissions',
            name='branches_d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissions',
            name='branches_e',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissions',
            name='branches_v',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissions',
            name='vendor_users_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissions',
            name='vendor_users_d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissions',
            name='vendor_users_e',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermissions',
            name='vendor_users_v',
            field=models.BooleanField(default=False),
        ),
    ]
