# Generated by Django 5.2.2 on 2025-07-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_rolepermissions_branches_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolepermissions',
            old_name='vendor_users_a',
            new_name='staff_a',
        ),
        migrations.RenameField(
            model_name='rolepermissions',
            old_name='vendor_users_d',
            new_name='staff_d',
        ),
        migrations.RenameField(
            model_name='rolepermissions',
            old_name='vendor_users_e',
            new_name='staff_e',
        ),
        migrations.RenameField(
            model_name='rolepermissions',
            old_name='vendor_users_v',
            new_name='staff_v',
        ),
    ]
