# Generated by Django 5.2.2 on 2025-07-21 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_rename_vendor_users_a_rolepermissions_staff_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='booking_source',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='booking_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.salonbranch'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.customer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Card', 'Card'), ('Wallet', 'Wallet'), ('Cash at Salon', 'Cash at Salon')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.salon'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='stylist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='users', to='App1.salonbranch'),
        ),
    ]
