# Generated by Django 5.2.2 on 2025-07-23 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_service_popular'),
        ('App1', '0009_remove_appointment_assigned_by_and_more'),
    ]

    operations = [
    ]
