# Generated by Django 5.2.2 on 2025-07-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_merge_20250723_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
