# Generated by Django 5.2.2 on 2025-08-04 05:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_remove_user_last_login_salon_salon_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$', 'Enter a valid IFSC code')])),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_contact_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_fund_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='App1.salon')),
            ],
        ),
    ]
