# Generated by Django 5.2.2 on 2025-08-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0013_bankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
