# Generated by Django 5.2.2 on 2025-08-06 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0015_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCodeForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.user')),
            ],
        ),
    ]
