# Generated by Django 5.2.2 on 2025-08-11 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0017_appointment_payment_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonserviceavailability',
            name='is_available',
        ),
        migrations.AddField(
            model_name='salonserviceavailability',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salonserviceavailability',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Vendor_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('week_no', models.IntegerField(blank=True, null=True)),
                ('week_start_date', models.DateField(blank=True, null=True)),
                ('week_end_date', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payout_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.salon')),
            ],
        ),
    ]
