# Generated by Django 5.2.2 on 2025-08-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0018_remove_salonserviceavailability_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonserviceavailability',
            name='is_avaiable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
