# Generated by Django 5.2.2 on 2025-08-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0019_salonserviceavailability_is_avaiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
