# Generated by Django 5.2.2 on 2025-08-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0020_appointment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
