# Generated by Django 5.2.2 on 2025-08-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0021_customer_fcm_token_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='otp_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
