# Generated by Django 5.2.2 on 2025-08-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0022_appointment_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fav_salons',
            field=models.ManyToManyField(blank=True, null=True, to='App1.salon'),
        ),
    ]
