# Generated by Django 5.2.2 on 2025-08-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0023_customer_fav_salons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
