# Generated by Django 5.2.2 on 2025-09-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0024_alter_customer_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Offline Booking', 'Offline Booking')], default='Pending', max_length=20),
        ),
    ]
